### ISSUE TITLE
add choices and  position field to letter, drop personal name

### ISSUE THREAD

**Issue by sirimainson** [AdaFactor/ResumeProject#31]
# Add to letter
- position choices
- position field

# Drop
- personal name in letter

**Comment by adadesions** [comment]
Ok got it!

**Comment by adadesions** [comment]
Hello please give me choices for positions^^ @sirimainson

**Comment by sirimainson** [comment]
# Choices for positions
- ผู้จัดการฝ่ายทรัพยากรบุคคล
- ผู้อำนวยการ
- อื่นๆ โปรดระบุ

**Comment by adadesions** [comment]
Thank you this issue gonna finish right now!
