### ISSUE TITLE
Need Edit button for CVs

### ISSUE THREAD

**Issue by adadesions** [AdaFactor/ResumeProject#41]
I found that we don't have a way to edit CV after created it, please add or find a cleaver way
to make CV editable^^

**Comment by sirimainson** [comment]
I can't migrate ("django.db.utils.ProgrammingError: column "user_id" named in key does not exist")
Do I need to drop database?

**Comment by adadesions** [comment]
Yes do the same things that we alway do
1. drop database
2. create database
3. remove all files in migrates folder except __inti__.py
4. Try to makemigrations and migrate again
5. praying
