### ISSUE TITLE
(Urgent!) I found footbar wrong diaplay in firefox

### ISSUE THREAD

**Issue by adadesions** [AdaFactor/ResumeProject#47]
Please help me fix footbar in firefox it's not belong in the right place. Check it every single pages
Thanks ^^

![screenshot from 2018-02-11 23-56-07](https://user-images.githubusercontent.com/3336816/36075891-6e121008-0f87-11e8-8dcb-edd82f7f86a8.png)

**Comment by sirimainson** [comment]
I fix footbar for firefox and PR already.
